## UAS-2 My Opinions

Masalah yang saya pilih: Konflik dan Perang


**1. Konflik merupakan hal yang natural**

Menurut saya, konflik merupakan suatu hal yang sangat wajar dan umum dialami dalam berkomunikasi. Pada dasarnya kita manusia adalah mahkluk sosial yang perlu berkomunikasi. Hal tersebut merupakan fondasi dari seluruh kultur, norma, dan bahkan konsep peradaban merupakan hasil dari kebutuhan kita untuk berkomunikasi. Namun saya merasa bahwa tidak semua komunikasi dapat membuahkan hasil baik. Orang bisa berdebat bisa marah, bisa mencaci-maki orang lain. Itu semua cara mengkomunikasikan ketidaksetujuan terhadap suatu pendapat, konsep, atau aksi. Namun cara melakukan hal tersebut perlu dikendalikan agar tidak membuat kerusakan yang lebih besar dari masalah yang seadanya. Bila terlalu ekstrim, seringkali terdengar bahwa orang lain melukai bahkan membunuh orang atas ketidaksepakatan. Baik dalam hal uang, hubungan, dan bahkan ideologi semua bentuk komunikasi bisa memicu konflik. 



**2. Tidak ada sisi yang "lebih benar" atau "lebih salah" dalam konflik**

Pada pertengahan hingga akhir abad ke-20, Amerika dan Rusia berada dalam perang "dingin" yang berasal atas ketidaksetujuan mereka atas ideologi yang dianuti masing-masing. Mereka tidak perang secara langsung dikarenakan ancaman dari kedua sisi yang saling memiliki senjata nuklir. Kedua sisi tahu bahwa bila mereka perang secara langsung, maka dunia pasti akan terluka berat dan tidak kecil kemungkinan untuk kedua sisi dan juga negara-negara lain punah akibatnya. Sebagai warga negara Indonesia yang sudah mendengarkan terlalu banyak mengenai PKI dan komunisme di Indonesia, saya merasa komunisme dan sosialisme itu tidaklah sebuah ideologi yang jahat. "From each according to their ability, To each according to their needs." Sistem yang diidamkan Karl Marx adalah sebuah utopia dimana semua manusia saling mencukupi dan melengkapi untuk hidup sejahtera. Namun sistem ini seringkali dijadikan "Iblis" oleh negara-negara barat dan bahkan Indonesia juga akibat praktiknya yang buruk dan cacat sehingga manusia yang hidup dibawah ideologi komunisme kebanyakan sengsara. 

Saya pernah mendengarkan pepatah dari Winston Churchill: "The inherent vice of capitalism is the unequal sharing of blessings; the inherent virtue of socialism is the equal sharing of miseries." Kapitalisme juga tidaklah secara langsung lebih baik dari komunisme. Kedua sisi hanya mencoba untuk melestarikan iman mereka dalam gaya dan pandangan hidup. Namun karena konflik antar ideologi yang tidak bisa saling menerima, maka fokusnya berpindah untuk menghancurkan sisi lawan karena mereka ingin menghancurkan kita. Disini menurut saya tidak ada yang bisa disalahkan. Memang rusia pada jaman USSR terkenal dalam kekejaman pemimpinnya. Namun pada akhirnya, orang-orang diminta untuk bertarung dengan orang lain karena ketidaksetujuan dalam pendapat beberapa orang saja. Hal ini dikecilkan dengan adanya indoktrinasi ideologi, namun bertarung untuk mempertahankan pandangan hidup mereka adalah hal yang tidaklah jahat ataupun buruk untuk dilakukan. 

Andaikan negara lain mengatakan bahwa ideologi pancasila kita merupakan ideologi yang jahat dan salah dan hanya membawa kesengsaraan pada rakyatnya dan ideologi mereka itu lebih benar dan baik untuk kita. Saya bisa membayangkan bagaimana reaksi warga dan pemerintah sendiri. Pada pandangan saya, konflik tidak memiliki sisi yang lebih benar atau salah. Dan dalam perang, hanya ada pemenang dan yang kalah.



**3. Dimana ada Manusia, selalu ada perpecahan dan konflik**

Semenjak jaman dahulu kala, sudah terekam dan terekap bahwa ada jutaan konflik, perang, dan pertempuran di sejarah manusia. Tidaklah peduli lokasi, abad, bahasa, dan lain sebagainya dimana ada manusia, pasti ada perang. Itulah opini saya yang berkaitan dengan opini saya yang sebelumnya juga. Saya sudah jelaskan bahwa sangat natural untuk terjadi konflik dalam berkomunikasi. Bila kita tidak berkomunikasi, maka konflik tidak akan ada. Memang komunikasi tidak selalu menimbulkan konflik. Namun konflik itu berasal dari isi komunikasi sendiri. Apabila komunikasi adalah pemicu konflik, maka secara asosiatif manusia adalah pembawa konflik. Menurut saya, selama manusia masih ada konflik dan perang tidak akan pernah hilang. Saya tapi juga sadar bahwa komunikasi juga pemicu perdamaian dan kesejahteraan. Komunikasi tidaklah sebuah hal yang baik. Namun dengan sifat komunikasi yang bisa memicu ketidaksetujuan atau perbedaan pendapat. Ada kemungkinan pihak yang berkomunikasi tidak menerimanya dengan baik, dan bisa memicu konflik. Maka itu menurut saya, manusia perlu mengetahui kepentingan toleransi, menghargai perbedaan pendapat, dan juga kesabaran.