# UTS-3 My Stories for You

**Sebuah cuplikan dari hidup saya**

Saya sudah bercerita tentang sejarah hidup saya secara singkat di page [All About Me](../All_About_me/index.qmd). Disana saya sebut bahwa saya adalah anak yang cengeng karena banyak teman kelas yang suka mengejek-ejek saya. Setiap kali saya mencoba bercurah hati ke orangtua ataupun guru, mereka hanya menganggap remeh dan tidak penting. Saya tidak tahu cara menghandal teman yang meledek saya tersebut. Saya diejek-ejek terus menerus hingga saya tidak tahan lagi dan mulai melawan secara fisik. Hal tersebut memang mengurangi ejekan terhadap saya (meskipun tidak banyak). Namun akibatnya saya semakin tidak memiliki teman. Saya juga tidak dapat mempercayai guru lagi akibat ada insiden di kelas 5 dimana guru wali kelas saya menganggap saya tidak sopan dan menarik saya pada leher ke ruang Bimbingan Konseling di Lantai 1 dari Lantai 2. Hal tersebut menghancurkan kemungkinan saya berteman dengan seorang guru lainnya di masa depan. 

Untungnya saya selama SMP ada grup teman yang bisa saya ajak bermain dan ngobrol. Grup kami mulai terbentuk di akhir SD/awal SMP. Kami bermain game bersama, mengerjakan tugas bersama, dan juga nongkrong dan jalan-jalan bersama. Saya merasa nyaman di lingkungan tersebut karena bisa dengan bebas tertawa, bersengang-senang, dan menunjukan diri saya. Namun di akhir kelas 9, "leader" grup teman tersebut mulai meng-ghosting saya dan beberapa teman lainnya karena alasan entah-apa. Orang yang meng-ghosting ini saya kira sangat dekat dengannya, kami selalu ngobrol setelah kelas berakhir ataupun saat istirahat, saling belajar, dan sangat sering bermain bersama. Maka itu saya lumayan kaget dan bingung mengapa Ia tidak lagi menjawab saya (ini pada masa covid). Saya mencoba mengkontak dan meminta maaf bila saya menyebutkan suatu hal yang salah, tapi tidak ada suara balasan apa-apa, hanya kesunyian. 

Setelah itu saya merasa terkucilkan kembali dan mulai depresi parah (Menyalahkan diri sendiri, Tidak merawat diri sendiri, Membenci diri, dan juga Keinginan Bunuh Diri). Saya pada masa tersebut merasa bahwa saya memang orang yang tidak pantas mendapat teman ataupun orang yang mempedulikan saya. Saya merasa semua hal buruk yang terjadi di masa lalu saya memang takdir karena diri saya yang memang tidak pantas merasakan kebahagiaan karena kejelekan diri saya. Bermacam-macam kalimat seperti itu muncul di kepala saya. Dan keluarga saya mencoba memberi saya layanan terapi ini itu namun tidaklah efektif sama-sekali. Dimana saya sudah merasa kehilangan kepercayaan kepada dunia, keluarga, teman, guru, diri sendiri, dan juga Tuhan, kondisi saya tidaklah bagus baik secara fisik ataupun mental. Tapi salah satu teman saya yang ikut di-ghosting tersebut menghubungi saya karena saya sudah jarang aktif online (ini masa covid). Saya bercerita sedikit tentang perasaan saya terhadap di-ghosting tersebut dan Ia mengatakan bahwa bukan hanya saya yang di-ghosting, memang beberapa orang lain dari grup pertemanan tersebut ikut di-ghosting. Saya tidak tahu hal ini sebelumnya, saya mengira hanya diri saya sendiri yang diperlakukan demikian. Ia mengajak saya ke grup orang yang ter-ghosting juga dan kita pada belajar bersama, bermain bersama, dan juga jalan-jalan bersama. Kini banyak yang berbeda sekolah dengan sesama beserta semakin jarang berkumpul karena kesibukan masing-masing. Meskipun alasan utamanya adalah dendam terhadap orang yang meng-ghosting tersebut, hubungan kami sangat erat.

Pesan moral dari cerita ini yang ingin saya sampaikan bukanlah untuk membawa dendam bersama-sama.

Pesan yang ingin saya sampaikan adalah: **Tidak semua orang itu baik dan dapat dipercaya. Namun juga tidak semua orang itu jahat dan tidak dapat dipercaya. Pada malam yang paling gelap sekalipun, pasti nantinya akan terbitlah pagi. Sekelam dan sepedihnya situasi apapun, bila kita bisa menjalaninya hingga akhir seberapa lamapun, maka pastinya akan ada akhir dari kepedihan tersebut.**