# UTS-1 All About Me

## **Pembuka**

"Fun" Facts diri saya:

**1. Saya buta warna parsial**

Lebih tepatnya buta warna merah-hijau. Atau istilah ilmiahnya itu *Deuteranopia*. Saya sering diketawain teman-teman saya dari dulu gara-gara tidak bisa membedakan warna-warna seperti hijau-cokelat, pink-abu, abu-hijau, hijau-biru, pink-ungu, dan lain-lain.

**2. Semua keluarga (utama) saya adalah alumni ITB**

Saya bagian dari STEI-K, Kakak saya bagian dari FSRD, Ibu dan Kakek bagian dari SAPPK, Ayah bagian dari FITB, dan Nenek bagian dari SF.

**3. Saya satu-satunya di keluarga yang tidak menggunakan kacamata**

Semua dari keluarga saya memiliki kelainan penglihatan (termasuk saya). Bedanya adalah saya jarak penglihatannya masih normal. Tapi mereka semua perlu kacamata yang "angka"-nya lumayan besar. Semoga tidak berubah, karena saya tidak begitu suka memakai kacamata.


## **Sejarah Diri Singkat**

Saya lahir di Bandung, 7 Mei 2006. Saya semenjak dahulu diajarkan oleh keluargaku untuk berbaik hati, berbagi, dan bersabar. Namun karena saya kurang diajarkan cara mengendalikan emosi dan amarah, saya menjadi anak yang sensi selama masa kecil. Saya pada umur 4 dimasukan ke Play-Group "Santa Angela" dimana saya akan disana hingga SMA. Pada masa TK dan SD, saya dikenal sebagai anak yang cengeng karena sering menangis setelah diledek-ledek oleh teman. Untungnya pada saat saya masuk SMP sudah mengurang. Pada masa saya kelas 8 hingga 11 ada wabah covid sehingga semua aktivitas akademik dijalankan secara daring. Akibatnya pertemanan saya tidak meluas dan itu-itu saja. Dan di pertengahan semester ganjil kelas 11, saya harus pindah ke homeschooling di sekolah "Pewaris Bangsa" akibat setelah pelajaran dijalankan secara tatap muka kembali saya mengalami masalah kesehatan berat. Meskipun demikian, saya masih dapat lolos masuk ke STEI-K ITB melalui jalur mandiri.

## **Hobi & Minat-Bakat**

Hobi saya adalah bermain game komputer, membaca buku, bermain catur, dan bermain badminton. Saya senang bermain game Dulu saya sering banget main game sampai orang tua saya lelah menegur saya. Saya sering membaca novel terutama genre mystery dan fantasy. Saya pernah mengikuti ekstrakurikuler catur dan badminton di SMP dan SD. Saya senang kedua kegiatan tersebut. Namun sayangnya saya kurang memiliki waktu untuk melakukan hal-hal tersebut akhir-akhir ini.

Minat saya adalah dalam bidang back-end, cybersec, dan software-engineering. Saya sudah mendalami programming semenjak sekitar kelas 4 SD. Dan saya terus mendalaminya hingga sekarang. Namun di masa SMA saya kurang mendalami karena sibuk untuk belajar ujian-ujian yang banyak, khususnya penerimaan mahasiswa baru. Namun semenjak di STEI-K saya semakin semangat mendalami kembali dunia programming.

## **Personality**

Karena sering-sering disuruh masukin MBTI untuk perkenalan-perkenalan, saya melakukan tesnya dan mendapatakn **INTJ**. Dan saya lumayan setuju dengan apa yang disebutkannya dan bahkan stereotip mereka. Saya adalah introvert yang lebih mudah lelah saat bersosialisasi dan berkomunikasi bahkan ke keluarga sendiri. Saya memiliki imaginasi yang luas dan seringkali melamun di kelas karena day-dreaming bila materinya membosankan. Selain itu saya sering banget over-thinking apalagi dalam konteks sosial. Saya membayangkan bila orang bertanya x ke saya saya jawabnya apa dan apabila saya jawab y, apa respon dari orang tersebut (mungkin itu kenapa saya lelah banget saat bersosialisasi). Saya selama masa kecil memang terlalu sensi, tapi sekarang saya kurang bisa peka terhadap keadaan emosi orang lain (dense/insensitive kata orang meh) karena saya fokus dengan logika dan pikiran aja. Dan saya juga suka hal-hal yang teratur. Saya hanya peduli kerapihan dari hal-hal yang menurut saya penting saja. Tapi bila saya anggap kurang penting saya jujur seringkali abaikan saja karena antara: 1. Beneran gak peduli, 2. Saya anggep kurang penting, atau 3. Pasrah atas keadaan dan merasa terlalu repot untuk saya organisir dan masuk mode priority management.

## **Values**

Ada beberapa nilai penting yang saya pegang selama hidup saya:

**1. Selalu bersikap adil ke semua orang**

Sebagai orang yang terundungi di masa lalu dan diabaikan oleh orangtua dan guru mengenainya, saya mengetahui apa rasanya diperlakukan tidak adil oleh orang lain. Maka itu saya akan selalu bersikap adil ke orang lain dan tidak memandang semata-mata saja.

**2. Selalu berbaik hati dan sopan ke orang lain hingga mereka tidak lagi layak menerimanya**

Melanjuti dari nilai sebelumnya, saya memiliki pandangan bahwa semua orang memiliki hak untuk dihormati, dihargai, dan diperlakukan dengan baik. Namun saya juga mengerti bahwa tidak semua orang bisa melakukan hal tersebut ke orang lain dan tidak semua orang layak untuk diperlakukan tersebut. Maka tanpa alasan yang jelas, semua orang akan saya hormati, harga, dan perlakukan dengan baik dan sopan hingga ada alasan yang tidak dapat diabaikan untuk tidak lagi memperlakukan orang dengan baik. 
(ini maksudnya jangan gak sopan atau jahat ke orang lain tanpa alasan jelas dan masuk akal, jangan gara-gara lagi bad mood tiba-tiba crash out ke orang lain sambil menghina dan memaki)

**3. Lakukan yang terbaik dan tetaplah maju kedepan apapun hasilnya**

Saya memandang bahwa bila mendapatkan kesusahan, kegagalan, dan kepedihan, menangis, kesal, marah, dan lainnya tidak akan membantu kita. Bila merasa ingin menyerah, saya mengingat lagi bahwa hidup hanya sekali saja dan kita hanya bisa menjalaninya dengan sebaik mungkin. Maka itu saya percaya bahwa meskipun kegagalan menunggu, jalanilah hingga akhirnya. Setidaknya jalanilah hidup anda hingga akhir.